# Generated by Django 3.1.1 on 2020-09-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200907_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('T', 'Text'), ('E', 'Email'), ('P', 'Phone'), ('A', 'Address')], max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.sections')),
            ],
        ),
    ]
